name: quantities

description: Physical quantities and units.

version: 0.0.2

homepage: https://github.com/mhmdanas/quantities

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  collection: ^1.14.0
  tuple: ^1.0.0
  meta: ^1.0.0

dev_dependencies:
  lint: ^1.2.0
  test: ^1.15.3
